-- window functions
-- json field extracts
-- corelarted queries
-- CTEs
-- date functions
 
 
------------------------------------------------------------------------------------------------------------------
WITH
------------------------------------------------------------------------------------------------------------------
WITH_CLAUSE1 AS (
SELECT DISTINCT
  FIELD38
  , JSON_EXTRACT_PATH_TEXT(JSON_EXTRACT_ARRAY_ELEMENT_TEXT(R.FIELD38, (JSON_ARRAY_LENGTH(R.FIELD38)-1)), 'login') AS FIELD31
  , JSON_EXTRACT_PATH_TEXT(JSON_EXTRACT_ARRAY_ELEMENT_TEXT(R.FIELD38, (JSON_ARRAY_LENGTH(R.FIELD38)-2)), 'login') AS FIELD32
  , JSON_EXTRACT_PATH_TEXT(JSON_EXTRACT_ARRAY_ELEMENT_TEXT(R.FIELD38, (JSON_ARRAY_LENGTH(R.FIELD38)-3)), 'login') AS FIELD33
  , COUNT(DISTINCT ID) AS FIELD34
  , COUNT(DISTINCT QUESTIONSTRING) AS FIELD35
  , COUNT(ID) AS FIELD36
  , SUM(SOME_FIELD/50+3) AS FIELD37
FROM TABLE1 R
WHERE TO_CHAR(R.ANOTHERDATE, 'YYYY-MM-DD') BETWEEN (TRUNC(ADD_MONTHS(DATE_TRUNC('Month', GETDATE()), -1))) AND (TRUNC(DATE_TRUNC('Month', GETDATE())) - interval '1 second')
AND R.FIELD10 NOT IN (SOME_INT)
AND NULLIF(SOME_FIELD,'') IS NOT NULL
AND FIELD39 IN ('SOME_STRING')
GROUP BY
FIELD38)
,
WITH_CLAUSE2 AS (
SELECT
  FIELD31
  , SUM(FIELD37) OVER (PARTITION BY FIELD31) AS WITH_CLAUSE2_SUM_FIELD31
  , SUM(FIELD36) OVER (PARTITION BY FIELD31) AS WITH_CLAUSE2_COUNT_FIELD31
  , SUM(FIELD34) OVER (PARTITION BY FIELD31) AS WITH_CLAUSE2_AVG_FIELD31
  , MAX(FIELD35) OVER (PARTITION BY FIELD31) AS WITH_CLAUSE2_UNIQUE_FIELD31
  , FIELD32
  , SUM(FIELD37) OVER (PARTITION BY FIELD32) AS WITH_CLAUSE2_SUM_FIELD32
  , SUM(FIELD36) OVER (PARTITION BY FIELD32) AS WITH_CLAUSE2_COUNT_FIELD32
  , SUM(FIELD34) OVER (PARTITION BY FIELD32) AS WITH_CLAUSE2_AVG_FIELD32
  , MAX(FIELD35) OVER (PARTITION BY FIELD32) AS WITH_CLAUSE2_UNIQUE_FIELD32
  
, FIELD33
  , SUM(FIELD37) OVER (PARTITION BY FIELD33) AS WITH_CLAUSE2_SUM_FIELD33
  , SUM(FIELD36) OVER (PARTITION BY FIELD33) AS WITH_CLAUSE2_COUNT_FIELD33
  , SUM(FIELD34) OVER (PARTITION BY FIELD33) AS WITH_CLAUSE2_AVG_FIELD33
  , MAX(FIELD35) OVER (PARTITION BY FIELD33) AS WITH_CLAUSE2_UNIQUE_FIELD33
FROM WITH_CLAUSE1)
,
WITH_CLAUSE3 AS (
SELECT DISTINCT
  FIELD31 AS WITH_CLAUSE2_NM
  , WITH_CLAUSE2_SUM_FIELD31 AS WITH_CLAUSE2_SUM
  , WITH_CLAUSE2_COUNT_FIELD31 AS WITH_CLAUSE2_COUNT
  , WITH_CLAUSE2_AVG_FIELD31 AS WITH_CLAUSE2_AVG
  , WITH_CLAUSE2_UNIQUE_FIELD31 AS FIELD35
FROM WITH_CLAUSE2
  WHERE NULLIF(FIELD31, '') IS NOT NULL  
UNION ALL
SELECT DISTINCT
  FIELD32 AS WITH_CLAUSE2_NM
  , WITH_CLAUSE2_SUM_FIELD32 AS WITH_CLAUSE2_SUM
  , WITH_CLAUSE2_COUNT_FIELD32 AS WITH_CLAUSE2_COUNT
  , WITH_CLAUSE2_AVG_FIELD32 AS WITH_CLAUSE2_AVG
  , WITH_CLAUSE2_UNIQUE_FIELD32 AS FIELD35
FROM WITH_CLAUSE2
  WHERE NULLIF(FIELD32, '') IS NOT NULL    
UNION ALL
SELECT DISTINCT
  FIELD33 AS WITH_CLAUSE2_NM
  , WITH_CLAUSE2_SUM_FIELD33 AS WITH_CLAUSE2_SUM
  , WITH_CLAUSE2_COUNT_FIELD33 AS WITH_CLAUSE2_COUNT
  , WITH_CLAUSE2_AVG_FIELD33 AS WITH_CLAUSE2_AVG
  , WITH_CLAUSE2_UNIQUE_FIELD33 AS FIELD35 
FROM WITH_CLAUSE2
  WHERE NULLIF(FIELD33, '') IS NOT NULL)
,
WITH_CLAUSE2_OVERALL AS (
SELECT DISTINCT
  WITH_CLAUSE2_NM
  , (SUM(WITH_CLAUSE2_SUM) /
          SUM(NULLIF(WITH_CLAUSE2_COUNT, 0))) AS FIELD24
  , CASE
      WHEN E.FIELD10 IN (SOME_INT1)
      THEN
        (SUM(WITH_CLAUSE2_SUM) /
          SUM(NULLIF(WITH_CLAUSE2_COUNT, 0))) * .20
      WHEN E.FIELD10 IN (SOME_INT2)
      THEN
        (SUM(WITH_CLAUSE2_SUM) /
          SUM(NULLIF(WITH_CLAUSE2_COUNT, 0))) * .15
      WHEN E.FIELD10 IN (SOME_INT3)
      THEN
        (SUM(WITH_CLAUSE2_SUM) /
          SUM(NULLIF(WITH_CLAUSE2_COUNT, 0))) * .10
    END AS FIELD25
  , SUM(WITH_CLAUSE2_COUNT) AS FIELD26
  , SUM(WITH_CLAUSE2_AVG) AS FIELD27
FROM WITH_CLAUSE3 S
  INNER JOIN 
    (SELECT DISTINCT
    FIELD40 AS FIELD02
    , FIELD10
    , RANK() OVER (PARTITION BY FIELD01 ORDER BY DATASET DESC) AS _RANK
    FROM TABLE2
    WHERE TO_CHAR(DATASET, 'YYYY-MM-DD') BETWEEN (TRUNC(ADD_MONTHS(DATE_TRUNC('Month', GETDATE()), - 1))) AND (TRUNC(DATE_TRUNC('Month', GETDATE())) - interval '1 second')
    AND FIELD10 IN (SOME_INT1, SOME_INT2, SOME_INT3)) E ON S.WITH_CLAUSE2_NM = E.FIELD02
  WHERE E._RANK = 1
  GROUP BY WITH_CLAUSE2_NM
          , E.FIELD10
  HAVING SUM(WITH_CLAUSE2_COUNT) > 4 AND SUM(WITH_CLAUSE2_AVG) > 1 AND MAX(FIELD35) > 0)
,
HCCALCTABLE AS (
SELECT DISTINCT
R.FIELD41
, SUM(CASE
        WHEN R.FIELD10 IN ('SOME_INT')
        THEN 1
        ELSE 0
      END) AS FIELD28
, SUM(CASE
        WHEN R.FIELD10 NOT IN ('SOME_INT')
        THEN 1
        ELSE 0
      END) AS FIELD29
FROM TABLE2 R 
INNER JOIN 
      (SELECT DISTINCT
        FIELD01
        , FIELD40
        , FIELD10
        , RANK() OVER (PARTITION BY FIELD01 ORDER BY DATASET DESC) AS _RANK
       FROM TABLE2
       WHERE TO_CHAR(DATASET, 'YYYY-MM-DD') BETWEEN (TRUNC(ADD_MONTHS(DATE_TRUNC('Month', GETDATE()), - 1))) AND (TRUNC(DATE_TRUNC('Month', GETDATE())) - interval '1 second')
       AND FIELD10 IN (SOME_INT1, SOME_INT2, SOME_INT3)) E 
           ON R.FIELD41 = E.FIELD40
WHERE TO_CHAR(DATASET, 'YYYY-MM-DD') BETWEEN (TRUNC(ADD_MONTHS(DATE_TRUNC('Month', GETDATE()), - 1))) AND (TRUNC(DATE_TRUNC('Month', GETDATE())) - interval '1 second')
AND E._RANK = 1
AND NULLIF(R.FIELD40, '') IS NOT NULL
AND NULLIF(R.FIELD41, '') IS NOT NULL
GROUP BY 
R.FIELD41
, E.FIELD10)
SELECT
FIELD01
, FIELD02
, FIELD03
, FIELD04
, FIELD05
, FIELD06
, CASE
      WHEN FIELD06 IN ('SOME_STRING1', 'SOME_STRING2')
        THEN 'SOME_STRING_NAME'
      WHEN FIELD06 IN ('SOME_STRING3', 'SOME_STRING4') 
        THEN 'SOME_STRING_NAME2'
      ELSE 'SOME_STRING_NAME3'
  END AS FIELD07
, FIELD08
, FIELD09
, FIELD10
, FIELD11
, FIELD12
, CASE 
    WHEN FIELD12 IN ('SOME_STRING5')
      THEN 'SOME_STRING_NAME4'
    WHEN FIELD12 LIKE '%SOME_STRING6%' OR FIELD09 LIKE '%SOME_STRING7%'
      THEN 'SOME_STRING_NAME5'
    WHEN FIELD12 IN ('SOME_STRING8') OR FIELD08 LIKE '%SOME_STRING9%'
      THEN 'SOME_STRING_NAME6'
    WHEN FIELD12 IN ('SOME_STRING10') OR FIELD08 LIKE '%SOME_STRING11%'
      THEN 'SOME_STRING_NAME7'
  END AS FIELD23
, O.FIELD24
, O.FIELD25
, O.FIELD26
, O.FIELD27
, CASE
    WHEN NULLIF(TEMP::CHAR,'') IS NULL THEN 0
    ELSE TEMP
  END AS FIELD28
, CASE
    WHEN NULLIF(BB::CHAR,'') IS NULL THEN 0
    ELSE BB
  END AS FIELD29
FROM 
  (SELECT DISTINCT
    FIELD30 AS FIELD02
    , FIELD01
    , FIELD04
    , FIELD05
    , FIELD03
    , FIELD06
    , FIELD08
    , FIELD09
    , FIELD10
    , FIELD11
    , FIELD12
    , RANK () OVER (PARTITION BY FIELD01 ORDER BY DATASET DESC) AS _RANK
   FROM TABLE2
   WHERE TO_CHAR(DATASET, 'YYYY-MM-DD') BETWEEN (TRUNC(ADD_MONTHS(DATE_TRUNC('Month', GETDATE()), - 1))) AND (TRUNC(DATE_TRUNC('Month', GETDATE())) - interval '1 second')
   AND FIELD10 IN (SOME_INT1, SOME_INT2, SOME_INT3)) E
INNER JOIN WITH_CLAUSE2_OVERALL O ON O.WITH_CLAUSE2_NM = E.FIELD02
LEFT JOIN HCCALCTABLE H ON H.FIELD41 = E.FIELD02
WHERE _RANK = 1
AND FIELD11 NOT IN ('SOME_STRING2')

